POST http://localhost:5000/analyse
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="blues.00002.wav"

< ./data/genres_original/blues/blues.00002.wav
--WebAppBoundary--

###
